version: 2
models:
  - name: products_silver
    config:
      contract:
        enforced: true
      description: "products table"
    columns: 
      - name: product_id
        data_type: bigint
        constraints:
          - type: not_null
        tests: [not_null, unique]
      - name: sku
        data_type: string
        constraints:
          - type: not_null
        tests: [not_null]
      - name: name
        data_type: string
        constraints:
          - type: not_null
        tests: [not_null]
      - name: category
        data_type: string  
        constraints:
          - type: not_null
        tests: 
          - not_null
          - accepted_values:        
              arguments:     
                values: ['Electronics','Apparel','Home Goods','Books','Beauty','Sports & Outdoors','Toys & Games']
      - name: subcategory
        data_type: varchar
        constraints:
          - type: not_null
        tests: 
          - not_null
          - accepted_values:        
              arguments:     
                values: ['Electronics','Apparel','Home Goods','Books','Beauty','Sports & Outdoors','Toys & Games']        
      - name: current_price
        data_type: double
        constraints:
          - type: not_null
        tests: [not_null]
      - name: currency
        data_type: string 
        constraints:
          - type: not_null
        tests: [not_null]
      - name: is_discontinued
        data_type: boolean
        constraints:
          - type: not_null
        tests: [not_null]
      - name: introduced_dt
        data_type: date  
        constraints:
          - type: not_null
        tests: [not_null]
      - name: discontinued_dt
        data_type: date
        constraints:
          - type: not_null
        tests: [not_null]
      - name: isDeleted
        data_type: string
        constraints:
          - type: not_null
        tests: [not_null]
      - name: ingestion_ts
        data_type: timestamp with time zone
        constraints:
          - type: not_null
        tests: [not_null]
      - name: src_filename
        data_type: string
        constraints:
          - type: not_null
        tests: [not_null]
      - name: src_hash
        data_type: string
        constraints:
          - type: not_null
        tests: [not_null]

   